### ISSUE TITLE
Vec2.cpp missing from Utils. Remove project dependency

### ISSUE THREAD

**Issue by physixtential** [JensDerKrueger/lnc#3]
The VS project doesn't compile because Vec2.cpp does not exist in the Utils directory. Remove Vec2.cpp from Quelldateien\Utils in the VS project to fix.

I tried to push the change myself, but I see the project does not allow random pushes.

**Comment by JensDerKrueger** [comment]
thanks for the info, I just fixed this issue with the latest commit
