### ISSUE TITLE
is this line correct?

### ISSUE THREAD

**Issue by Harasz2020** [JensDerKrueger/lnc#52]
the line is:
      const uint8_t v = getLumiValue(x,height-y);
shouldnt that be
      const uint8_t v = getLumiValue(x,height-y-1);
?
https://github.com/JensDerKrueger/lnc/blob/6bfa77b534fafc69d93e642eb237dec286c1b507/cpp/OpenGL/Utils/Image.cpp#L128

**Comment by JensDerKrueger** [comment]
yep, that's a bug, nw fixed
