### ISSUE TITLE
SOS, SOS, navigation Error on MS Asteroida

### ISSUE THREAD

**Issue by Harasz2020** [JensDerKrueger/lnc#55]
Admiral!

Our Communication officers have recieved SOS from MS Asteroida. The ship has been lost in asteroid belt Githubin.
Probably **due to a Bug-Fix** in the navigation Software (order of Matrix multiplication) the Code running the Ship was compromised and accidentally **replaced by a trivial students learning Code template**.
Further actions needed!

More details here:
https://github.com/JensDerKrueger/lnc/blob/7094c337c57946d2f5c8c7c112cd2eb5a1ed22ec/cpp/OpenGL/19_Asteroids/main.cpp

**Comment by JensDerKrueger** [comment]
oops, what happened ...

**Comment by JensDerKrueger** [comment]
Major Tom to Ground Control: [...] And I'm floating in a most peculiar way

**Comment by Harasz2020** [comment]
Ground Control to Major Tom: Roger that, Communication re established, all Systems online.
personal note: Fly how ever you want, there is plenty of space. But dont fly to high...
Over and out.
