### ISSUE TITLE
Menger predicate class

### ISSUE THREAD

**Issue by CueXXIII** [JensDerKrueger/lnc#65]
Meine Idee von gestern, die Anzahl der "1"-Ziffern in Base 3 Darstellung der Koordinaten zu zählen konnte ich durch scharfes hinschauen fixen. Man muß die Anzahl der "1"en in jeder Stelle (≙ Tiefe des Menger-Schwamms) zählen.

https://paste.debian.net/1221320/
https://paste.debian.net/plain/1221320 (für Download)

Der Constructor der Klasse berechnet die Zifferndarstellungen vor, was auch den Code des Prädikates deutlich vereinfacht.

Da der Menger-Schwamm Code noch nicht im Repository ist, konnte ich die Ergebnisse noch nicht vergleichen.

**Comment by JensDerKrueger** [comment]
Schaue ich heute Abend mir mal an. Hier ist übrigens die rekursive Lösung die die Zellen setzt, sie ist auf jeden Fall mal sehr kurz und übersichtlich:

  const std::array< Vec3ui ,20> offsets = {
    Vec3ui{0,0,0},Vec3ui{1,0,0},Vec3ui{2,0,0},
    Vec3ui{0,1,0},              Vec3ui{2,1,0},
    Vec3ui{0,2,0},Vec3ui{1,2,0},Vec3ui{2,2,0},
    Vec3ui{0,0,1},              Vec3ui{2,0,1},
    Vec3ui{0,2,1},              Vec3ui{2,2,1},
    Vec3ui{0,0,2},Vec3ui{1,0,2},Vec3ui{2,0,2},
    Vec3ui{0,1,2},              Vec3ui{2,1,2},
    Vec3ui{0,2,2},Vec3ui{1,2,2},Vec3ui{2,2,2}
  };

  void construct(size_t x, size_t y,size_t z, size_t depth) {
    if (depth == 0) 
      setVoxel(x,y,z,true);
    else
      for (const Vec3ui& p : offsets) {
        construct(x*3+p.x, y*3+p.y, z*3+p.z, depth-1);
      }
  }

**Comment by JensDerKrueger** [comment]
ooops, weg sind die Einrückungen ... naja das ganze muss dann nur noch mit construct(0,0,0,depth); aufgerufen werden

**Comment by CueXXIII** [comment]
Sieht gut aus, die Ausgabe ist identisch bis Level 6, 7 läuft grade noch.
